FERREMAS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('WEBSITE.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

WEBSITE/urls.py
from django.urls import path
from .views import * # no olvidar agregar msg para las notificaciones despues
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('base',Base,name='base'), 
    path('woi',Woi,name='woi'), 
    path('accounts/register',Register,name='register'),
    path('',Landing,name='landing'),
    path('agregar/', Agregar, name='agregar'),
    path('editar/<int:pk>', Editar, name='editar'),
    path('update_producto/', Updateproducto, name='update_producto'),
    path('eliminar/<int:pk>', Eliminar, name='eliminar'),
    path('bodega/', Bodega, name='bodega'),
    path('list/', List, name='list'),
    path('catalogo/', Catalogo, name='catalogo'),
    path('catalogo/<int:id_producto>', Detalle, name='Detalle'),
    path('carrito/',VerCarrito,name='VerCarrito'),
    path('carrito/add',AñadirCarritoCompra,name='AñadirCarritoCompra'),
    path('carrito/upd',ActualizarCantidadCarrito, name="ActualizarCantidadCarrito"),
    path('carrito/del',QuitarCarritoCompra,name='QuitarCarritoCompra'),
    path('resultadopago/<str:rp>',ResultadoPago,name='Resultadopago'),
    path('quienesSomos/',quienesSomos,name="quienesSomos"),
    path('contacto/',contacto,name="contacto"),
    path('cuenta/',Cuenta,name="Cuenta"),
    path('preprarPedido/',prepararPedido,name="prepararPedido"),
    path('finanzas/',finanzas, name="finanzas")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WEBSITE/models.py
from django.db import models
from django.contrib.auth.models import User
# CATEGORIA DEL PRODUCTO
class Categoria(models.Model):
    id_categoria = models.AutoField(db_column="id_categoria", primary_key=True)
    nombre_categoria = models.CharField(max_length=45)

    def __str__(self):
        return str(self.nombre_categoria)   

class Marca(models.Model):
    id_marca = models.AutoField(db_column="id_marca", primary_key=True)
    nombre_marca = models.CharField(max_length=45)
    

    def __str__(self):
        return str(self.nombre_marca)

 #Producto
class Producto(models.Model):
    id_producto = models.AutoField(db_column="id_producto", primary_key=True)
    nombre_producto = models.CharField(max_length=100, blank=False)
    precio = models.IntegerField(blank=False)
    descripcion = models.CharField(max_length=400, blank=False)
    cant_inventario = models.IntegerField(default=0)
    id_categoria = models.ForeignKey(
        "Categoria", on_delete=models.CASCADE, db_column="id_categoria"
    )
    id_marca = models.ForeignKey(
        "Marca", on_delete=models.CASCADE, db_column="id_marca"
    )

    def __str__(self):
        return str(self.nombre_producto)
    
class Imagen_producto(models.Model):
    id_imagen_p = models.AutoField(db_column="id_imagen_p", primary_key=True)
    imagen_producto = models.FileField(upload_to="productos/", null=True)
    id_producto = models.ForeignKey(
        "Producto", on_delete=models.CASCADE, db_column="id_producto"
    )

    def __str__(self):
        return str(self.id_imagen_p)

class Estado(models.Model):
    id_estado = models.AutoField(db_column='id_envio', primary_key=True, default=None)
    nombre = models.CharField(max_length=100, null=False, default='Pendiente')

    def __str__(self):
        return self.nombre

class Info_cliente(models.Model):
    id_info = models.AutoField(db_column="id_info", primary_key=True)
    nombre = models.CharField(max_length=25)
    apellido = models.CharField(max_length=25)
    rut = models.CharField(max_length=15)
    direccion = models.CharField(max_length=80)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, db_column='usuario', null=True)

class Pedido(models.Model):
    id_pedido = models.AutoField(db_column='id_pedido', primary_key=True, default=None)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, db_column='usuario', null=True)
    fecha = models.DateField(auto_now_add=True)
    id_envio = models.ForeignKey('Estado', on_delete=models.CASCADE, db_column='id_envio')
    id_carrito = models.ForeignKey('Carrito', on_delete=models.CASCADE, db_column='id_carrito', default=None)
    
    def __str__(self):
        return str(self.fecha)

    @property
    def total(self):
        carrito_cont = Carrito_item.objects.filter(id_carrito=self.id_carrito)
        subTotal= sum([item.cantidad* item.id_producto.precio for item in carrito_cont])
        return subTotal

    @property
    def items(self):
        carrito_cont = Carrito_item.objects.filter(id_carrito=self.id_carrito)
        return carrito_cont

class Carrito(models.Model):
    id_carrito = models.AutoField(db_column='id_carrito',primary_key=True,default=None)
    estado = models.IntegerField(default=0)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, db_column='usuario', null=True)

class Carrito_item(models.Model):
    id_carrito= models.ForeignKey('Carrito', on_delete=models.CASCADE, db_column='id_carrito',default=None)
    id_producto= models.ForeignKey('Producto', on_delete=models.CASCADE, db_column='id_producto')
    cantidad = models.PositiveIntegerField(default=0,null=True,blank=False)
    @property
    def sub_total(self):
        sub_total=self.cantidad * self.id_producto.precio
        return sub_total
    
class Direccion(models.Model):
    id_direccion = models.AutoField(db_column='id_direccion',primary_key=True,default=None)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, db_column='usuario', null=True)
    calle = models.CharField(max_length=200, null=False)
    numeracion = models.IntegerField(null=False, blank=False, default=None)
    comuna = models.CharField(max_length=100, null=False, default=None)
    region = models.CharField(max_length=100, null=False, default=None)
    def __str__(self):
        return self.calle

WEBSITE/views.py
from django.shortcuts import render, redirect
import django_filters 
import matplotlib.pyplot as plt
import io
import urllib, base64
from django.shortcuts import render, get_object_or_404, redirect
from django_filters import DateFilter
from django.shortcuts import get_object_or_404 
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
import requests
from .models import *
from django.db.models import Q
from .utils import get_dollar_value

# SDK de Mercado Pago (si da problemas, instalar con: pip install mercadopago)
import mercadopago
# Agrega credenciales
sdk = mercadopago.SDK("TEST-937485966507246-051120-5327fec403daba4a078a7d4a79547a6a-1774376550")
# Nombre de usuario comprador de prueba: TESTUSER518394180
# Contraseña: cCnwPtzVxv

def Base(request):

    if request.user.groups.filter(name="vendedor").exists():
        grupo = "vendedor"
    elif request.user.groups.filter(name="bodeguero").exists():
        grupo = "bodeguero"
    elif request.user.groups.filter(name="contador").exists():
        grupo = "contador"
    else:
        grupo = "cliente"

    context = {
        "grupo": grupo,
    }

    return render(request,'base.html', context)

def Woi(request):
    if request.user.groups.filter(name="vendedor").exists():
        grupo = "vendedor"
    elif request.user.groups.filter(name="bodeguero").exists():
        grupo = "bodeguero"
    elif request.user.groups.filter(name="contador").exists():
        grupo = "contador"
    else:
        grupo = "cliente"

    context = {
        "grupo":grupo
    }
    return render(request, 'woi.html',context)

# VISTA LANDING
def Landing(request):

    if request.user.groups.filter(name="vendedor").exists():
        grupo = "vendedor"
    elif request.user.groups.filter(name="bodeguero").exists():
        grupo = "bodeguero"
    elif request.user.groups.filter(name="contador").exists():
        grupo = "contador"
    else:
        grupo = "cliente"

    if request.user.is_authenticated:
        user_id = request.user.id
    else:
        # Manejar el caso del usuario no autenticado
        return redirect('login')  # Redirige al usuario a la página de inicio de sesión
    usuario = request.user
    carrito = Carrito.objects.filter(estado=0,usuario=usuario).first()
    contador=Carrito_item.objects.filter(id_carrito=carrito).count()

    context = {
        "contador" : contador,
        "grupo":grupo
    }
    return render(request, 'landing.html',context)

# formulario para registrarse
class FormularioRegistro(UserCreationForm):
    email = forms.EmailField(
        max_length=254, help_text="Required. Enter a valid email address."
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        
# VISTA REGISTRO
def Register(request):

    if request.method == "POST":
        form = FormularioRegistro(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            Carrito.objects.create(usuario=user,estado=0)
            return redirect("landing")
    else:
        form = FormularioRegistro()

    return render(request, 'registration/register.html',{"form":form})

    
#VISTA PARA AGREGAR NUEVOS PRODUCTOS
@login_required
def Agregar(request):
    if request.user.groups.filter(name="vendedor").exists():
        grupo = "vendedor"
    elif request.user.groups.filter(name="bodeguero").exists():
        grupo = "bodeguero"
    elif request.user.groups.filter(name="contador").exists():
        grupo = "contador"
    else:
        grupo = "cliente"


    cat = Categoria.objects.raw("select * from website_categoria")
    marcas = Marca.objects.raw("select * from website_marca")

    if request.method == "POST":
        nombre_producto = request.POST["nombre"]
        precio = request.POST["precio"]
        descripcion = request.POST["descripción"]
        categoria = request.POST["categoria"]
        marcaProd = request.POST["marca"]
        objCategoria = Categoria.objects.get(id_categoria=categoria)
        objMarca = Marca.objects.get(id_marca=marcaProd)
        objProducto = Producto.objects.create(
            nombre_producto=nombre_producto,
            precio=precio,
            descripcion=descripcion,
            id_categoria=objCategoria,
            id_marca=objMarca
        )

        imagen = request.FILES.get("imagen")
        Imagen_producto.objects.create(
            imagen_producto=imagen,
            id_producto=objProducto
        )

        #Creación del diccionario para enviar los datos a la API
        datos_api = {
                "id_producto": None,
                "nombre_producto": nombre_producto,
                "precio": precio,
                "descripcion": descripcion,
                "stock_bodega": 50,  # Inicialmente todo producto nuevo creado comienza con 50 stock en bodega
                "id_marca": marcaProd,
                "id_categoria": categoria,
                "grupo":grupo
            }

        #Envío de los datos a la API
        requests.post('http://localhost/api/api/post.php?', json=datos_api)



        context = {
            "mensaje": "Oferta publicada exitosamente",
            "grupo": grupo,
            "cat": cat,
            "marca": marcas
            }
        return render(request, "agregar.html", context)
    else:
        context = {
            "grupo": grupo,
            "cat": cat,
            "marca": marcas
            }
        return render(request, "agregar.html", context)
    
from django.shortcuts import render, get_object_or_404, redirect
from .models import Producto, Categoria, Imagen_producto
from django.http import HttpResponseBadRequest

def Editar(request, pk):
    grupo = "cliente"
    if request.user.groups.filter(name="vendedor").exists():
        grupo = "vendedor"
    elif request.user.groups.filter(name="bodeguero").exists():
        grupo = "bodeguero"
    elif request.user.groups.filter(name="contador").exists():
        grupo = "contador"


    cat = Categoria.objects.all()

    cat = Categoria.objects.raw("select * from website_categoria")
    marcas = Marca.objects.raw("select * from website_marca")


    try:
        producto = Producto.objects.get(id_producto=pk)
        context = {
            "mensaje": "Editar Producto",
            "grupo": grupo,
            "cat": cat,
            "producto": producto,
        }
        return render(request, "editar.html", context)
    except Producto.DoesNotExist:
        context = {
            "mensaje": "Oferta no encontrada!",
            "grupo": grupo,
            "cat": cat,
        }
        return render(request, "list.html", context)
            "marca": marcas,
            "producto": producto
            }
            return render(request, "editar.html", context)
    except:
            context = {
            "mensaje": "Oferta no encontrada!",
            "grupo": grupo,
            "cat": cat,
            "marca": marcas
            }
            return render(request, "list.html", context)


def Updateproducto(request):
    grupo = "cliente"
    if request.user.groups.filter(name="vendedor").exists():
        grupo = "vendedor"
    elif request.user.groups.filter(name="bodeguero").exists():
        grupo = "bodeguero"
    elif request.user.groups.filter(name="contador").exists():
        grupo = "contador"

    cat = Categoria.objects.all()


    if request.method == "POST":
        id_producto = request.POST.get("id_producto")
        nombre_producto = request.POST.get("nombre")
        precio = request.POST.get("precio")
        descripcion = request.POST.get("descripcion")
        categoria_id = request.POST.get("categoria")

        if not (id_producto and nombre_producto and precio and descripcion and categoria_id):
            return HttpResponseBadRequest("Todos los campos son obligatorios")

        try:
            producto = Producto.objects.get(id_producto=id_producto)
            objCategoria = Categoria.objects.get(id_categoria=categoria_id)

            producto.nombre_producto = nombre_producto
            producto.precio = precio
            producto.descripcion = descripcion
            producto.id_categoria = objCategoria
            producto.save()

            imagen = request.FILES.get("imagen")
            if imagen:
                Imagen_producto.objects.filter(id_producto=producto).delete()
                Imagen_producto.objects.create(
                    imagen_producto=imagen,
                    id_producto=producto
                )

            context = {
                'mensaje': "Se guardaron los cambios hechos en la oferta",
                "grupo": grupo,
                "cat": cat,
                "producto": producto,
            }
            return render(request, 'editar.html', context)

    cat = Categoria.objects.raw("select * from website_categoria")
    marcas = Marca.objects.raw("select * from website_marca")

    if request.method == "POST":
        id_producto = request.POST["id_producto"]
        nombre_producto = request.POST["nombre"]
        precio = request.POST["precio"]
        descripcion = request.POST["descripción"]
        categoria = request.POST["categoria"]
        marcaProd = request.POST["marca"]
        objCategoria = Categoria.objects.get(id_categoria=categoria)
        objMarca = Marca.objects.get(id_marca=marcaProd)

        objProducto = Producto()
        objProducto.id_producto = id_producto
        objProducto.nombre_producto = nombre_producto
        objProducto.precio = precio
        objProducto.descripcion = descripcion
        objProducto.id_categoria = objCategoria
        objProducto.id_marca = objMarca

WEBSITE/templates/bodega.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="/static/CSS/styleAgregar.css">
{% endblock %}

{% block container %}  
<div class="container">
    <table class="table">
      <thead>
          <tr>
          <th>id producto</th>
          <th>Nombre producto</th>
          <th>Precio</th>
          <th>Descripción</th>
          <th>Editar</th>
          <th>Eliminar</th>
          </tr>
      </thead>
      <tbody>
          {% for item in producto %}
          <tr>
          <td>{{ item.id_producto }}</td>
          <td>{{ item.nombre_producto }}</td>
          <td>{{ item.precio }}</td>
          <td>{{ item.descripcion }}</td>

          {% endfor %}
        </tbody>
    </table>
              <center><button class="btt btn btn-outline-primary" onclick="history.back()">Volver</button></center>
          
            </form>
          </div>
  
        </div>
    
     
  {% endblock %}

WEBSITE/templates/carrito.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="/static/CSS/styleCarrito.css">
{% endblock %}

{% block container %}
<div class="row rowCarrito justify-content-center" >
  <div class="col-12 col-md-8 overflow-auto">
    <div class="d-flex justify-content-between">
      <a href="{% url 'catalogo' %}" class="text-white my-2 btn continuar">
        <i class="bi bi-bag-plus me-2"></i>Continuar Comprando
      </a>
      <form method="POST">
        {%csrf_token%}
        <input class="my-2 btn btn-outline-danger" type="submit" value="Vaciar Carrito" name="borrarTodo" formaction="{% url 'QuitarCarritoCompra' %}">
      </form>
    </div>
    
    {% for obj in contCarrito %}
    <div class="card mb-3">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <div class="d-flex flex-row align-items-center">
            <div>
              <img src="{{obj.id_producto.imagen_producto_set.first.imagen_producto.url}}" class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
            </div>
            <div class="ms-3">
              <h5>{{obj.id_producto.nombre_producto}}</h5>
              <p class="small mb-0">Marca: {{obj.id_producto.id_marca}}</p>
              <p class="small mb-0">Tipo: {{obj.id_producto.id_categoria}}</p>
            </div>
          </div>
          <div class="">
            <form method="POST" class="d-flex flex-row align-items-center">
              {% csrf_token %}
              <input type="hidden" name="id_producto" id="id_producto" value="{{obj.id_producto.id_producto}}">
              <input type="hidden" name="id_carrito" value="{{obj.id_carrito.id_carrito}}">
              <div id="boton-actualizar" style="display: flex; align-items: center;">
                <p class="button-text" style="margin: 0; padding: 10px 0;">Cambiar cantidad</p>
                <button class="bi bi-pencil-square btn btn-act" style="padding: 5px; margin-left: 5px;" formaction="{% url 'ActualizarCantidadCarrito' %}"></button>
              </div>
              <div style="width: 90px;" class="me-2 d-flex">
                <input class="fw-normal mb-0 form-control bg-light text-dark border-dark" type="number" value="{{obj.cantidad}}" id="cantidad-producto" name="cantidad" min="1">
              </div>
              <div> 
                <h5 class="prices ms-2 me-2 productPrice"> {{obj.sub_total}}</h5>
              </div>
              <input class="btn btn-outline-danger" type="submit" name="borrarUno" value="Quitar" formaction="{% url 'QuitarCarritoCompra' %}">
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    
  </div>
  <div class="col-12 col-md-4">
    <div class="checkout card text-white rounded-3 my-2">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <h5 class="mb-0">Direccion de Envio</h5>
        </div>
        <form class="mt-4" method="POST">{%csrf_token%}
          <div class="row mb-4">
            <div class="col-md-6">
              <div class="form-outline form-white">
                <input type="text" name="region" class="form-control form-control-lg" placeholder="Metropolitana" required/>
                <label class="form-label" for="typeExp">Region</label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-outline form-white">
                <input type="text" name="comuna" class="form-control form-control-lg" placeholder="La Cisterna" required/>
                <label class="form-label" for="typeText">Comuna</label>
              </div>
            </div>
          </div>
          <div class="row mb-4">
            <div class="col-md-6">
              <div class="form-outline form-white">
                <input type="text" name="calle" class="form-control form-control-lg" placeholder="Av. Calle" required>
                <label class="form-label" for="typeExp">Calle</label>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-outline form-white">
                <input type="number" name="numeracion" class="form-control form-control-lg" placeholder="1234" required/>
                <label class="form-label" for="typeText">Numeracion</label>
              </div>
            </div>
          </div>
        
        <hr class="my-4">
        <div class="d-flex justify-content-between">
          <p class="mb-2">Subtotal</p>
          <p class="mb-2 prices productPrice">{{subTotal}}</p>
        </div>
        <div class="d-flex justify-content-between">
          <p class="mb-2">Envío</p>
          <p class="mb-2 prices productPrice">2500</p>
        </div>
        <div class="d-flex justify-content-between mb-4">
          <p class="mb-2">Total</p>
          <p class="mb-2 prices productPrice">{{total}}</p>
        </div>
        {% if subTotal > 0 %}
        <input type="hidden" value="{{carro.id_carrito}}" name="carro">
        <button class="btn btn-info btn-block btn-lg" type="submit" formaction="{{url}}">
          <div class="d-flex justify-content-between">
            <a type="submit">
              <span>Pagar<i class="bi bi-bag-check-fill ms-2"></i></span>
            </a>
          </div>
        </button>
        {% endif %}
      </form>
      </div>

    </div>
  </div>
</div>


{% endblock %}

WEBSITE/templates/catalogo.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="/static/CSS/styleCatalogo.css">
{% endblock %}

{% block container %}

  <div class="container ps-5 pe-5">

    <div class="row mt-5 catalogRow">
  <!-- Filtros -->
          <div class="col-2 filters">
            <h1 class="filterTitle mt-3 mb-3"><i class="bi bi-funnel-fill"></i>Filtros</h1>
            <form role="form product-form" method="GET">
              <div class="form-group">
                <label>Palabra clave</label>
                <input type="text" class="form-control" name="palabra_clave">
              </div>
              <!-- filtro Categoria -->
              <div class="form-group">
                <label>Tipo Producto</label>
                <select class="form-control" name="tipo_producto">
                  <option selected value="">...</option>
                  {% for categoria in categorias %}
                  <option value="{{categoria.id_categorias}}">{{categoria.nombre_categoria}}</option>
                  {% endfor %}
                </select>
              </div>
              <!-- filtro Marca -->
              <div class="form-group">
                <label>Marca</label>
                <select class="form-control" name="marca">
                  <option selected value="">...</option>
                  {% for marca in marcas %}
                  <option value="{{marca.id_marca}}">{{marca.nombre_marca}}</option>
                  {% endfor %}
                </select>
              </div>
              <!-- filtro precio -->
              <div class="form-group mb-3">
                <label>Ordenar por Precio</label>
                <select class="form-control" name="precio">
                  <option selected value="">...</option>
                  <option value="1">Menor Precio</option>
                  <option value="2">Mayor Precio</option>
                </select>
              </div>
              <!-- filtro disponible -->
              <div class="text-center">
                <button class="buy btn filter p-2" type="submit"><i class="bi bi-filter-circle-fill"></i> Filtrar</button>
              </div>
            </form>

          </div>
<!-- Cards de productos -->        
        <div class="col-8 catalogCol">
          <div class="row catalogRow">
            {% for producto in productos %}
              <div class="col-3 productCard m-1 p-2 me-5 mb-3">
                <span class="productCategory p-1"> {{ producto.id_categoria.nombre_categoria  }}</span>
                <div class="productPhoto">
                  <img src="{{ producto.imagen_producto_set.first.imagen_producto.url }}" class="card-img-top" alt="...">
                </div>
                <div class="productDetail">
                  <h4 class="productName">{{ producto.nombre_producto }}</h4>
                  <p class="productBrand">{{ producto.id_marca }}</p>
                  <h3 class="productPrice">{{producto.precio}}</h3>
                  <p>${{ producto.precio_en_dolares}} USD</p>
                  <h3></h3>
                </div>
                <div class="productButtons">
                  <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" value="{{producto.id_producto}}" name="id_producto">
                    <input type="hidden" value="1" name="cantidad">
                    {% if producto.stock_bodega < 1 %}
                    
                    <button class="buy btn btn-lg">
                      <span><i class="bi bi-bag-x-fill"></i> Sin Stock</span>
                    </button>
                    {% else %}
                      <button class="buy btn btn-lg" type="submit" formaction="{% url 'AñadirCarritoCompra' %}">
                        <span><i class="bi bi-bag-check-fill"></i> Comprar</span>
                      </button>
                    {% endif %}
                    
                  </form>
                  <a class="buy more btn btn-lg" href="{% url 'Detalle' producto.id_producto %}">
                    <span><i class="bi bi-plus-circle-fill"></i> Ver Mas</span>
                  </a>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
        
      </div>
    </div>
      
  
    

{% endblock %}

WEBSITE/templates/cuenta.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="/static/CSS/styleCuenta.css">
{% endblock %}

{% block container %}

<div class="row d-flex justify-content-center align-items-center">
    <div class="col-10 col-md-10 h-100 overflow-auto">
      <div class="card" style="border-radius: 10px;">
        <div class="card-header px-4 py-4">
          <h5 class="text-muted mb-0">Mis Pedidos</h5>
        </div>
        {% for pedido in pedidos %}
          <div class="card mt-3">
            <div class="card-header pt-2">
              <h5 class="text-muted">Pedido: ABC200567-{{pedido.id_pedido}}</h5>
            </div>
            <div class="card-body">
              {% for item in items %}
                {% if item.id_carrito == pedido.id_carrito %}
                  <div class="row">
                    <div class="col-md-3 pb-2">
                      <img src="{{ item.id_producto.imagen_producto_set.first.imagen_producto.url }}" class="img-fluid rounded" style="height: 10vh; width: 8vw;" alt="Phone">
                    </div>
                    <div class="col-md-3 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0">{{ item.id_producto.nombre }}</p>
                    </div>
                    <div class="col-md-3 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small">Cantidad: {{item.cantidad}}</p>
                    </div>
                    <div class="col-md-3 text-center d-flex justify-content-center align-items-center">
                      <p class="text-muted mb-0 small productPrice">{{item.sub_total}}</p>
                    </div>
                    <hr>
                  </div>
                {% endif %}
              {% endfor %}
              <div class="d-flex justify-content-between pt-2">
                <p class="fw-bold mb-0">Detalle de su orden</p>
                <div class="d-flex">
                  <p class="me-2">Total:</p>
                  <p class="text-muted mb-0 productPrice"> {{pedido.total}}</p>
              </div>
              </div>
              <div class="d-flex justify-content-between pt-0">
                <p class="text-muted mb-0">Numero de pedido: ABC200567-{{pedido.id_pedido}}</p>
              </div>
              <div class="d-flex justify-content-between">
                <p class="text-muted mb-0">Fecha: {{pedido.fecha}}</p>
                <p class="text-muted mb-0"><span class="fw-bold me-4"></span></p>
              </div>
              <div class="d-flex justify-content-between mb-2">
                <p class="text-muted mb-0"></p>
                <p class="text-muted mb-0"><span class="fw-bold me-4"></span> </p>
              </div>
              <div class="row d-flex align-items-center justify-content-center">
                  <div class="col-md-10">
                    <div class="progress" style="height: 6px; border-radius: 16px;">
                      {% if pedido.id_envio.nombre == 'Pendiente' %}
                      <div class="progress-bar" role="progressbar" style="width: 15%; border-radius: 16px; background-color:  #014F98;" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
                      {% elif pedido.id_envio.nombre == 'En Despacho' %}
                      <div class="progress-bar" role="progressbar" style="width: 65%; border-radius: 16px; background-color:  #014F98;" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
                      {% elif pedido.id_envio.nombre == 'Entregado' %}
                      <div class="progress-bar" role="progressbar" style="width: 100%; border-radius: 16px; background-color:  #014F98;" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"></div>
                      {% endif %}
                  </div>
                    <div class="d-flex justify-content-around mb-1">
                      <p class="text-muted mb-0 small">Preparando su pedido</p>
                      <p class="text-muted mt-1 mb-0 small ms-xl-5">Su pedido esta en despacho</p>
                      <p class="text-muted mt-1 mb-0 small ms-xl-5">Pedido entregado</p>
                    </div>
                  </div>
                </div>
            </div>
            <div class="card-footer border-0 px-3 py-2"
              style="background-color: #014F98; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

WEBSITE/templates/woi.html
{% extends "base.html" %}
{% load static %}

{% block container %}

<center><img src="{% static 'IMG/wiuc.gif'  %}" alt="" style="height: 70vh; width: 50%; border-radius: 25px; " class="mt-2 mb-2"></center>

{% endblock %}